### ISSUE TITLE
$store.getters.translation undefined error

### ISSUE THREAD

**Issue by nicofonseca** [hjeti/vue-skeleton#14]
Hi DJ HJ! 🎵 

Your starter is amazing, but I had some issues.

When using the multi-language site and want to access the Vuex of the translations, for example, **_this.$store.getters.translation.home.title_**, Vue does not yet recognize any translation property and throw **undefined error**. This happens only if we load the site for the first time on the page that requires that store. The weird is that if I enter the site with the second language it works correctly.

### **src/config/config.js**
```javascript
variables: {
 [VariableNames.LOCALE_ENABLED]: true,
 [VariableNames.LOCALE_ROUTING_ENABLED]: true,
}

properties: {
 [PropertyNames.DEFAULT_LOCALE]: 'en-gb',
 [PropertyNames.AVAILABLE_LOCALES]: ['en-gb','es-es'],
}
```

### **static/locale/en-gb.json**
`{
    "home":{
        "title":"page home"
    }
}`
### **static/locale/es-es.json**
`{
    "home":{
        "title":"página home"
    }
}`

### **src/page/HomePage/HomePage.js**
```javascript
export default {
 name: 'HomePage',
 mounted(){
  console.log(this.$store.getters.translation.home.title);
 }
};
```

If the error is mine do not hesitate to tell me. And thanks for sharing this starter. 💋 💋

**Comment by hjeti** [comment]
Hey Nico,

I've checked your problem and found the root of the issue. The localeLoader fires the callback before vue-i18n-manager processes the loaded file ( I can't change the order because it works with a promise that resolves with the language data). That is why the language data is not there in the mounted function. Normally this is not a problem because we always use [$t()](https://matteogabriele.gitbooks.io/vue-i18n-manager/content/translate.html) in templates and that is reactive, so it will update whenever the translation updates. If you still want to use the getters you can resolve the issue by adding a timeout before calling the resolve of the `waitForLocale` function in the `startUp.js`. 

```javascript
const waitForLocale = store =>
	new Promise(resolve => {
		if (localeLoader.isLoaded(store.getters.currentLanguage.code)) {
			resolve();
		} else {
			localeLoader.setLoadCallback(locale => {
				if (locale === store.getters.currentLanguage.code) {
					setTimeout(() => {
						resolve();
					});
				}
			});
		}
	});
```
I will add this fix to the skeleton to prevent issues like this.

**Comment by hjeti** [comment]
I've added the timeout in the localeLoader which is a better solution. See [commit].(https://github.com/hjeti/vue-skeleton/commit/bfbb52b646505ca37cb9ccdd8d247c384f5c1c32)
