### ISSUE TITLE
Private keys should not be public

### ISSUE THREAD

**Issue by ArmandBiteau** [hjeti/vue-skeleton#52]
[key.pem](https://github.com/hjeti/vue-skeleton/blob/master/build-tools/ssl/key.pem) located in /build-tools/ssl/ causes issues on repos such as [http://agency-code.googlesource.com/](http://agency-code.googlesource.com/).
Private keys should not be in the repo's history, to ensure a smooth sync between git remotes.

The fix requires tools like BFG: 
`bfg --delete-files key.pem`
but can be quite dangerous if not used very carefully.

**Comment by ThaNarie** [comment]
It's a demo/debug-only key for local development if you need HTTPS support. It's not a key from the user.

**Comment by ThaNarie** [comment]
After checking with Armand offline, I now see how it can be an issue. Not with the skeleton itself, but with projects that have the file in it and will later need to push to another remote that doesn't allow that file anywhere in the history.

I'm not sure how that detection works (looking at extension, or file content), so we could do a few things:
* rename the file (will not work if file contents is checked)
* give a clear error message when the file is missing, and one of these options:
  * have the user create it by hand, by providing the right commands
  * have the user download the file from somewhere (not sure where in github)
  * have a script generate the file automatically (and print out info that it did, maybe ask question first)
  * have a script download it automatically (still, not sure where to store it)

Not sure if we want to keep it in the repo after user created it, probably put it in the gitignore by default, since we could have the scenario where it's not allowed at the origin, but you do want to test locally.

**Comment by hjeti** [comment]
We can do what webpack-dev-server does and that is generating a fake certificate at runtime. 
See: 
https://github.com/webpack/webpack-dev-server/blob/69a90c7edc1983b4ffd968c829bb0d6f543f74dd/lib/Server.js#L400

**Comment by hjeti** [comment]
Or implement this library that can generate fake certificates. So we don't have to write any code:

https://www.npmjs.com/package/pem
