### ISSUE TITLE
It would be ideal if pre-commit only lints staged changes

### ISSUE THREAD

**Issue by MattijsKneppers** [hjeti/vue-skeleton#63]
Currently, the longer a project gets, the longer a commit takes to complete linting, regardless of whether you are committing a large multi-file refactor or just a one-liner change.

**Comment by hjeti** [comment]
We use lint-staged that will only lint and prettify staged files as far as I know. So it shouldn't take more time.

**Comment by petervdn** [comment]
I do get errors on files that are unstaged, preventing me from committing the staged ones.

**Comment by MattijsKneppers** [comment]
`that will only lint and prettify staged files as far as I know` Is there a way to test this? 

I get the same as Peter, when a file that is not staged violates prettier rules, I still can't commit. Also when pre-commit is in package.json, commit times are a lot longer, even if I commit only 1 file that is ignored by prettier.

**Comment by ThaNarie** [comment]
Not sure if relevant, but I noticed a difference between other configurations.

Other config:
```
      "src/**/*.{js,ts,scss,json}": [
        "prettier --write",
        "git add"
      ],
      "src/**/*.js": [
        "npm run lint:js"
      ],
      "src/**/*.ts": [
        "npm run lint:ts"
      ],
      "src/**/*.scss": [
        "npm run lint:css"
      ]
```

vue-skeleton (simplified):
```
const defaultSettings = ['prettier --write', 'git add'];

module.exports = {
  'src/**/*.js': [...defaultSettings, 'npm run lint:js'],
  'src/**/*.vue': ['npm run lint:js'],
  'src/**/*.ts': [...defaultSettings, 'npm run lint:ts'],
  'src/**/*.scss': [...defaultSettings, 'npm run lint:scss'],
};
```

The difference is that `prettier --write` and `git add` is run separately for each file type, not sure if that creates overhead, it shouldn't have a difference on _what_ files gets included though.

Now more to the point, It could also be the way we call the linter. In the examples I could find it would just run `eslint`, which will actually execute `eslint file.js file2.js`.
We call the linter as `npm run lint:js` which calls `eslint src ....` (it includes the targeted files), which will result in `eslint src ... file.js file2.js`, which still includes the src folder.

We still want to keep parts of the other config params (like supported extensions or link to a config file, and the --cache flag), so we need to copy that over the the lint-stage configuration (not a nice solution, since you'll have the same config in two places).

**Comment by hjeti** [comment]
Yes if that is the problem the only way to fix it is to copy the command. Will look into it.

**Comment by hjeti** [comment]
I did a quick test and that is indeed the problem will create a fix right now.
