### ISSUE TITLE
Remove RoutePaths.js

### ISSUE THREAD

**Issue by ThijsTyZ** [hjeti/vue-skeleton#66]
In my opinion it is very confusing that we have the RouteNames.js and the RoutePaths.js. In practice I see a lot of developers using the RouteNames in one file and RoutePaths in an other, which leads to unclear code.

I think we should always use the route name for navigation and only the path for the declaration. Therefor there is no need to have a separate RoutePaths file. So the RoutePaths file should be removed.

**Comment by ThaNarie** [comment]
So you're saying:

1. remove `RoutePaths.js`

2. Declare the paths directly in the `routes.js`, and make the `name` prop required for all routes.

3. Never use `router.push({ path: ... })`, but always `router.push({ name: ... , params: ... })` (same with `<router-link :to=...>`)

Sounds reasonable, unless someone knows of a case where they specifically needed a path?

**Comment by ThijsTyZ** [comment]
Yes, that is what I am saying.

**Comment by hjeti** [comment]
I also saw that people use both so it's oke to remove the paths. So maybe the solution of @flut1 is a nice one where everything is in one place.

But I think there are also more advanced cases where you want access to the actual path instead of name only. We can ignore those cases in the skeleton and if you want to use it you can create your own implementation. In the case of @flut1 solution just creating an extra object in the routes that declare the paths as well. We can maybe make that clear in the documentation if we want to force people use names by removing the paths.
