### ISSUE TITLE
Discussion about the usage of constants in the store.

### ISSUE THREAD

**Issue by ThijsTyZ** [hjeti/vue-skeleton#67]
I think the current implementation of a store is over complicated and inconsistent. Specially the way we use the index.js file with the constants.

Or we should go all the way with constants and use them everywhere. Or we are not using them at all.

If we go all the way, then we should use constants not only for mutations (btw I think we should name them "{{name_pc}}Mutations" instead of "{{name_pc}}MutationTypes", they are not "type" of mutations, they are all normal mutations) but for everything. So also for the values, the getters and so on. But this will lead to  very unclear code. Even within a simple example:

```
export const Values = {
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
};

export const Getters = {
  FULL_NAME: 'fullName',
};

export default {
  namespaced: true,
  state: {
    [Values.FIRST_NAME]: 'John',
    [Values.LAST_NAME]: 'Do',
  },
  getters: {
    [Getters.FULL_NAME]: ({ [Values.FIRST_NAME]: firstName, [Values.LAST_NAME]: lastName }) =>
      `${firstName} ${lastName}`,
  },
};
```

Compared that to:

```
export default {
  namespaced: true,
  state: {
    firstName: 'John',
    lastName: 'Do',
  },
  getters: {
    fullName: ({ firstName, lastName }) => `${firstName} ${lastName}`,
  },
};
```

Although I am normally a huge fan of using constants, I think for this case it will only add unnecessary clutters and complexity. And this is not (In my opinion) what Vue is designed for. So I would suggest to remove all the constants in the store.

**Comment by flut1** [comment]
Agreed. Though this solution (removing the constants entirely) would conflict with the solutions in #36 (improving how we write the constants). 

I very much agree that the constants as they are now have too much complexity and clutter. If we don't find a better way to write them maybe removing them is indeed the best solution. One road I think that might be worth investigating is if we can remove `namespaced: true`. It seems to be the cause of a lot of clutter around defining these constants.

**Comment by hjeti** [comment]
I am not a fan of completely removing all constants that way there is no way of knowing where data is coming from in the store. I agree that the current solution is not good that's why we already have the other ticket with some great solutions to solve store issues.

I would also never use constants for state because that doesn't work and looks ugly. For example you can have nested objects in there. But we already know that is bad so non of the proposed solutions to this problem have constants for state. 

Removing the namespaced boolean of each store can lead to conflicting actions, mutations and getters. 

The whole reason I created two versions of each constant. Namespaced and non namespaced is because of easy support for vuex-connect that didn't support the namespaces. It's not clear if they support it now, but I never heard that anybody used it in a project or even looked into using it in a project. So we can remove a lot of complexity by dropping support for vuex-connect. Then we have only 1 constant for each action/getter/mutation and 1 constant for the namespace. And they can be all in the file itself so we can get rid of the index.js. By doing this we also get rid of the 'magic' in the proposed solutions. 

And you can just use the getters/actions/mutations like this:
```js
...mapGetters(UserNamespace, {
   [FULLNAME]: 'fullName'
})
```
This also removes the easy possibility to use dispatch in components. I am not a fan of that at all I think we should always use the map functions in components. 
You still have the possibility to dispatch when you want to do something in the startup for example:

```js
store.dispatch(`${UserNamespace}/${SET_FIRST_NAME}`, 'Peter');
```

**Comment by gianko** [comment]
Other solution is to remove the namespace and do it by hand

```
const USER_CONST = {
  SET_FIRST_NAME: 'user/setFirstName',
}
```

**Comment by hjeti** [comment]
@gianko yes that is maybe a good idea. It's basically the same as we do in react actions. In that case we can get rid of the namespaced is true. And all the namespace complexity is completely removed. And this also gives us the ability to handle one action in multiple stores.

**Comment by n0cha** [comment]
I agree with Thijs that the constants are responsible for a lot of clutter and redundancy. However, I do believe they serve a purpose, mainly to help prevent breakage when changing around the names or structure of the store (which in my personal experience happens a lot).
Nevertheless, when I started on my first project here and saw the Vue skeleton, I quickly became annoyed with the cumbersome, verbose and repetitive nature of the store, so I did the following:

I combined the index.js file with the moduleName.js file and defined the names of state, actions, mutations and getters as follows:
```
const ACTIONS = {
  SEARCH: '',
  // etc
};
```

The constants are called STATE, ACTIONS, MUTATIONS and GETTERS. This is because I consider PascalCased names to be reserved for constructors and data types, and camelCased names would collide with the function parameter names. And, well, they're constants. The key names don't necessarily have to be uppercase and according to Airbnb they shouldn't be, but that's a matter of personal preference.

I leave the values undefined (or empty strings in this case, because it's less typing) and use a line of code to automatically set them. This reduces human error and maintenance:
```
[VALUES, ACTIONS, MUTATIONS, GETTERS].forEach(constants =>
  Object.keys(constants).forEach(key => {
    constants[key] = key;
  }),
);
```

Exporting the namespaced constants is done by a simple line that maps the objects using lodash's mapValues, e.g.:
```
export const DataMutationTypes = mapValues(MUTATIONS, value => `${DataNamespace}/${value}`);
```
(Yes, following the convention mentioned above, "DataMutationTypes" should be capitalised. And I also fully agree with Thijs that they are not "MutationTypes" etc., but simply "Mutations". So this should export DATAMUTATIONS, but I chose to not go tearing down that particular edifice yet.)

Both of these should of course be extracted to utility functions if commonly used.

The result is a single file which internally uses locally namespaced constants, like so:
```
[GETTERS.FULL_NAME]: state => `${state[STATE.FIRST_NAME]} ${state[STATE.LAST_NAME]}`,
```
Still much longer than Thijs' suggestion, but as you can see I use a slightly different notation (no destructuring of the state argument) to arrive at a more concise and readable result (or at least I think so).

This single file can then (and probably should) be split up to separate files for state, getters, mutations and actions when it becomes too large, but that's a story for a different thread.
