### ISSUE TITLE
issues running dev server on https + ios 

### ISSUE THREAD

**Issue by petervdn** [hjeti/vue-skeleton#74]
i have had a few projects were i was not able to run the devserver (with https set to true) on ios. iirc, the page seemed to be constantly refreshing itself

**Comment by hjeti** [comment]
It's because of this issue:

https://stackoverflow.com/questions/40376471/safari-refresh-loop-with-webpack-dev-server-in-https-mode

There is a workaround: Enabling inline on webpack-dev-server. So if you want to test on ios with https enable it and disable it again later. 

https://webpack.js.org/configuration/dev-server/#devserver-inline
